/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author alejo
 */
public class RegistroPropietario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPropietario
     */
    public RegistroPropietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFinalizarPropietario = new javax.swing.JButton();
        labelGetWorkPropietario = new javax.swing.JLabel();
        labelNombreNegocio = new javax.swing.JLabel();
        textNombreNegocio = new javax.swing.JTextField();
        labelTipoServicio = new javax.swing.JLabel();
        textTipoServicio = new javax.swing.JTextField();
        labelNumeroProductos = new javax.swing.JLabel();
        textNumeroProductos = new javax.swing.JTextField();
        labelLinkPagina = new javax.swing.JLabel();
        textLinkPagina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonFinalizarPropietario.setText("FINALIZAR");
        buttonFinalizarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFinalizarPropietarioActionPerformed(evt);
            }
        });

        labelGetWorkPropietario.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        labelGetWorkPropietario.setText("GrowLocal");

        labelNombreNegocio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombreNegocio.setText("Nombre Negocio");

        labelTipoServicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTipoServicio.setText("Tipo Servicio");

        labelNumeroProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNumeroProductos.setText("Numero Productos");

        labelLinkPagina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLinkPagina.setText("Link Pagina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonFinalizarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNombreNegocio)
                        .addComponent(textNombreNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelGetWorkPropietario)
                        .addComponent(labelTipoServicio)
                        .addComponent(textTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNumeroProductos)
                        .addComponent(textNumeroProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelLinkPagina)
                        .addComponent(textLinkPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(labelGetWorkPropietario)
                .addGap(59, 59, 59)
                .addComponent(labelNombreNegocio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombreNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTipoServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNumeroProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumeroProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelLinkPagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLinkPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(buttonFinalizarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFinalizarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFinalizarPropietarioActionPerformed
        Screen s2 = new Screen();
        s2.setVisible(true);
    }//GEN-LAST:event_buttonFinalizarPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFinalizarPropietario;
    private javax.swing.JLabel labelGetWorkPropietario;
    private javax.swing.JLabel labelLinkPagina;
    private javax.swing.JLabel labelNombreNegocio;
    private javax.swing.JLabel labelNumeroProductos;
    private javax.swing.JLabel labelTipoServicio;
    private javax.swing.JTextField textLinkPagina;
    private javax.swing.JTextField textNombreNegocio;
    private javax.swing.JTextField textNumeroProductos;
    private javax.swing.JTextField textTipoServicio;
    // End of variables declaration//GEN-END:variables
}
