/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.growlocal.growlocal;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Account extends javax.swing.JPanel {

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        this.txt_email.setText("Email");
        this.txt_pass.setText("Contraseña");
        this.txt_emailR.setText("Email");
        this.txt_rpassR.setText("Repite tu contraseña");
        this.txt_passR.setText("Contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_emailR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_rpassR = new javax.swing.JTextField();
        txt_passR = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txt_error1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_error2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));

        jPanel1.setBackground(new java.awt.Color(57, 62, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 204, 163));
        jLabel1.setText("INICIA SESION");

        txt_email.setBackground(new java.awt.Color(238, 238, 238));
        txt_email.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(35, 41, 49));
        txt_email.setText("jTextField1");
        txt_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 3));
        txt_email.setName("email_txt"); // NOI18N
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focs(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focsl(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_pass.setBackground(new java.awt.Color(238, 238, 238));
        txt_pass.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(35, 41, 49));
        txt_pass.setText("jTextField2");
        txt_pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 3));
        txt_pass.setName("pass_txt"); // NOI18N
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focs2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focs2l(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(57, 62, 70));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txt_emailR.setBackground(new java.awt.Color(238, 238, 238));
        txt_emailR.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_emailR.setForeground(new java.awt.Color(35, 41, 49));
        txt_emailR.setText("jTextField1");
        txt_emailR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 3));
        txt_emailR.setName("email_txt"); // NOI18N
        txt_emailR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focs3(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focsl3(evt);
            }
        });
        txt_emailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 204, 163));
        jLabel2.setText("REGISTRATE");

        txt_rpassR.setBackground(new java.awt.Color(238, 238, 238));
        txt_rpassR.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_rpassR.setForeground(new java.awt.Color(35, 41, 49));
        txt_rpassR.setText("jTextField1");
        txt_rpassR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 3));
        txt_rpassR.setName("email_txt"); // NOI18N
        txt_rpassR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focs4(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focsl4(evt);
            }
        });
        txt_rpassR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rpassRActionPerformed(evt);
            }
        });

        txt_passR.setBackground(new java.awt.Color(238, 238, 238));
        txt_passR.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_passR.setForeground(new java.awt.Color(35, 41, 49));
        txt_passR.setText("jTextField1");
        txt_passR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 3));
        txt_passR.setName("email_txt"); // NOI18N
        txt_passR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focs5(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                focsl5(evt);
            }
        });
        txt_passR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passRActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(57, 62, 70));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(35, 41, 49));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(238, 238, 238));
        jButton2.setText("Registrarme");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_error1.setForeground(new java.awt.Color(78, 204, 163));
        txt_error1.setText("...");
        txt_error1.setToolTipText("");

        jButton3.setBackground(new java.awt.Color(35, 41, 49));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(238, 238, 238));
        jButton3.setText("Iniciar Sesion");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_error2.setForeground(new java.awt.Color(78, 204, 163));
        txt_error2.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_error1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass)
                                    .addComponent(txt_email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_error2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_emailR, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_passR, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_rpassR, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(21, 21, 21)))
                                        .addGap(21, 21, 21)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_error1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_emailR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_passR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_rpassR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_error2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //boton registro
        String emailR = txt_emailR.getText().toLowerCase();
        String passR = txt_passR.getText();
        String rpassR = txt_rpassR.getText();

        if (emailR.isEmpty() || passR.isEmpty() || rpassR.isEmpty()){
            //
            JOptionPane.showMessageDialog(this, "Un campo esta vacio");

        }else{
            if(passR.equals(rpassR)){
                GrowLocal.addToFb(emailR, passR);
            }else{JOptionPane.showMessageDialog(this, "Las contraseñas tienen que ser iguales");}

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_passRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passRActionPerformed

    private void focsl5(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focsl5
        // TODO add your handling code here:
        if(this.txt_passR.getText().equals(""))
        this.txt_passR.setText("Contraseña");
    }//GEN-LAST:event_focsl5

    private void focs5(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs5
        // TODO add your handling code here:
        if(this.txt_passR.getText().equals("Contraseña"))
        this.txt_passR.setText("");
    }//GEN-LAST:event_focs5

    private void txt_rpassRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rpassRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rpassRActionPerformed

    private void focsl4(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focsl4
        // TODO add your handling code here:
        if(this.txt_rpassR.getText().equals(""))
        this.txt_rpassR.setText("Repite tu contraseña");
    }//GEN-LAST:event_focsl4

    private void focs4(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs4
        // TODO add your handling code here:
        if(this.txt_rpassR.getText().equals("Repite tu contraseña"))
        this.txt_rpassR.setText("");
    }//GEN-LAST:event_focs4

    private void txt_emailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailRActionPerformed

    }//GEN-LAST:event_txt_emailRActionPerformed

    private void focsl3(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focsl3
        // TODO add your handling code here:
        if(this.txt_emailR.getText().equals(""))
        this.txt_emailR.setText("Email");
    }//GEN-LAST:event_focsl3

    private void focs3(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs3
        // TODO add your handling code here:
        if(this.txt_emailR.getText().equals("Email"))
        this.txt_emailR.setText("");
    }//GEN-LAST:event_focs3

    private void focs2l(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs2l
        // TODO add your handling code here:
        if(this.txt_pass.getText().equals(""))
        this.txt_pass.setText("Contraseña");
    }//GEN-LAST:event_focs2l

    private void focs2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs2
        // TODO add your handling code here:
        if(this.txt_pass.getText().equals("Contraseña"))
        this.txt_pass.setText("");
    }//GEN-LAST:event_focs2

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void focsl(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focsl
        // TODO add your handling code here:
        if(this.txt_email.getText().equals(""))
        this.txt_email.setText("Email");
    }//GEN-LAST:event_focsl

    private void focs(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focs
        // TODO add your handling code here:
        if(this.txt_email.getText().equals("Email"))
        this.txt_email.setText("");
    }//GEN-LAST:event_focs

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String email = txt_email.getText();
        String password = txt_pass.getText();
        GrowLocal.searchInFb(email, password);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailR;
    private javax.swing.JLabel txt_error1;
    private javax.swing.JLabel txt_error2;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_passR;
    private javax.swing.JTextField txt_rpassR;
    // End of variables declaration//GEN-END:variables
}
